language: objective-c
osx_image: xcode7.3

before_script:
- carthage version
- xcrun simctl list
#- time xcodebuild -showBuildSettings
- carthage bootstrap --use-submodules --platform ios,osx
- SIMULATOR_ID=$(xcrun instruments -s | grep -o "iPhone 6 (9.3) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")

script:
- echo $SIMULATOR_ID
- open -b com.apple.iphonesimulator --args -CurrentDeviceUDID $SIMULATOR_ID
- set -o pipefail
- xcodebuild -project ObservableArray-RxSwift.xcodeproj -scheme ObservableArray-iOS test -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" | xcpretty -c
- xcodebuild -project ObservableArray-RxSwift.xcodeproj -scheme ObservableArray-Mac test -sdk macosx | xcpretty -c
- pod lib lint --quick

after_success:
- bash <(curl -s https://codecov.io/bash)
