language: objective-c
osx_image: xcode8.2

before_script:
- brew upgrade carthage >> /dev/null
- carthage version
- xcrun simctl list
- time xcodebuild -showBuildSettings
- carthage bootstrap --no-use-binaries --use-submodules --platform ios,osx,tvos
- SIMULATOR_ID=$(xcrun instruments -s | grep -o "iPhone 7 (10.0) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")

script:
- echo $SIMULATOR_ID
- open -b com.apple.iphonesimulator --args -CurrentDeviceUDID $SIMULATOR_ID
- set -o pipefail
- xcodebuild -project ObservableArray-RxSwift.xcodeproj -scheme ObservableArray-iOS test -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7" | xcpretty -c
- xcodebuild -project ObservableArray-RxSwift.xcodeproj -scheme ObservableArray-Mac test -sdk macosx | xcpretty -c
- xcodebuild -project ObservableArray-RxSwift.xcodeproj -scheme ObservableArray-tvOS test -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 1080p" | xcpretty -c
- pod lib lint --quick

after_success:
- bash <(curl -s https://codecov.io/bash)
